spring.application.name=activiti

# H2 em memória e console web
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.datasource.url=jdbc:h2:mem:flowable-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Flowable
flowable.database-schema-update=true
flowable.check-process-definitions=true
flowable.async-executor-activate=false

# Logging útil
logging.level.org.flowable=INFO
logging.level.org.springframework.web=INFO
